### ISSUE TITLE
Extensive real world test suite

### ISSUE THREAD

**Issue by roll** [okfn/datapackage-bigquery-py#5]
Datapackage sources:
- https://github.com/datasets
- https://github.com/os-data
- https://github.com/openspending/fiscal-data-package-demos

Tested datapackages:
- [ ] country-codes (required field issue - https://github.com/okfn/jsontableschema-py/pull/45)
- [ ] country-list (encoding problem)
- [ ] currency-codes (not valid datapackage - https://github.com/datasets/currency-codes/pull/6, https://github.com/datasets/currency-codes/issues/2)
- [ ] finance-vix (type support - https://github.com/okfn/jsontableschema-bigquery-py/issues/1)
- [x] gb-country-regional-analysis (reduced, minor tweaks)
- [ ] gb-country-regional-analysis (not valid datapackage)
- [ ] gdp (type support - https://github.com/okfn/jsontableschema-bigquery-py/issues/1)
- [ ] imf-weo (required field issue - https://github.com/okfn/jsontableschema-py/pull/45)
- [ ] language-codes (required field issue - https://github.com/okfn/jsontableschema-py/pull/45)
- [ ] population (invalid data package - https://github.com/datasets/population/pull/2)
- [ ] registry (required field issue - https://github.com/okfn/jsontableschema-py/pull/45)
- [ ] s-and-p-500 (invalid data package - https://github.com/datasets/s-and-p-500/pull/3)
- [ ] s-and-p-500-companies (required field issue - https://github.com/okfn/jsontableschema-py/pull/45)
- [x] testing
- [ ] un-locode (required field issue - https://github.com/okfn/jsontableschema-py/pull/45)

**Comment by roll** [comment]
https://github.com/okfn/datapackage-storage-py/issues/1
